name: PHP Code Formatter

on:
    push:
        branches:
            - main # O la rama que estés usando, ej: backend
permissions:
    contents: write
    pull-requests: write

jobs:
    formatting:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2" # Asegúrate que coincida con tu versión

            - name: Install dependencies
              run: composer install

            - name: Run PHP Code Beautifier and Fixer
              run: vendor/bin/phpcbf
              continue-on-error: true # <--- AÑADE ESTA LÍNEA

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Fix: Apply PSR-12 code style fixes"
                  branch: ${{ github.head_ref }}
